image: node:20

include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - local: '.lint.yml'

stages:
  - build
  - test



Build system:
  stage: build
  
  script:
    - echo "Building..."


Code Linting:
  stage: test
  
  script:
    - npm run lint

Unit tests:
  stage: test
  
  script:
    - npm test

