image: node:20

include:
  - local: '.lint.yml'

stages:
  - build
  - lint
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm ci

build-system:
  stage: build
  script:
    - echo "Building..."

unit-tests:
  stage: test
  script:
    - npm test
  variables:
    DB_CONNECTION_STRING: "mongodb://localhost:55000/testdb"
