image: node:20

include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - local: '.lint.yml'

stages:
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm ci

build-system:
  stage: build
  script:
    - echo "Building..."

code-linting:
  stage: test
  script:
    - npm run lint

unit-tests:
  stage: test
  script:
    - npm test
