ariables:
  LINT_RC: "https://gitlab.lnu.se/pipelines/stages/-/raw/master/lint/eslint/.eslintrc.json"


################################################################
#                     Development pipeline                     #
# ------------------------------------------------------------ #
# This pipeline will run for every new commit or MR except for #
# MR:s to the submit branch.                                   #
################################################################
Code linting:
  stage: lint
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != 'release' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != 'lnu/submit'
  before_script:
    - npx install-peerdeps --dev @lnu/eslint-config
  script:
    - |
      echo "Downloading rc-file from: $LINT_RC"
      curl $LINT_RC > .eslintrc.json
      npx eslint .
